"""
extractor/gazetteer.py — Maintained reference set of known threat-intel names.

This replaces the "reject if on a hand-grown denylist" approach with "accept if
it matches a maintained reference set of *known-good* entities (or has entity
shape)".  The reference set is a bundled snapshot of public taxonomies (MITRE
ATT&CK via MISP galaxy + MISP threat-actor / ransomware / malware clusters),
regenerated by ``scripts/update_gazetteer.py``.

Matching is done on a canonical key (casefold + strip separators + drop
non-alphanumerics) so "Cobalt Strike", "cobalt-strike" and "CobaltStrike" all
resolve to the same entry, matching the canonicalisation used by
``extractor.normalizer.canonicalize_entity_value`` for name types.

Never raises: if the snapshot is missing the sets are empty and every lookup
returns ``False`` — the shape checker then carries the accept/reject decision on
its own, so extraction degrades gracefully rather than breaking.

Public interface
----------------
is_known_actor(name)       → bool
is_known_malware(name)     → bool
is_known_ransomware(name)  → bool
is_known(name, category)   → bool   (category in {"threat_actor","malware","ransomware"})
category_of(name)          → str | None
lookup(name, category=None) → dict | None (canonical, synonyms, uuid)
stats()                    → dict
"""

from __future__ import annotations

import json
import logging
import os
import re
import unicodedata
from typing import Any, Optional

logger = logging.getLogger(__name__)

_DATA_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data",
    "threat_gazetteer.json",
)
_DOMAIN_STOPWORDS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data",
    "domain_stopwords_en.txt",
)

# Organisation suffixes are also generic name qualifiers when they appear on
# an actor/malware candidate (for example, ``LockBit Ransomware Group``).
# Keep this set here so gazetteer matching and shape validation use the same
# vocabulary without introducing a circular import through entity_shape.
ORG_SUFFIXES: frozenset[str] = frozenset({
    "inc", "incorporated", "llc", "ltd", "limited", "corp", "corporation",
    "gmbh", "ag", "sa", "srl", "bv", "plc", "co", "company", "group",
    "holdings", "technologies", "systems", "solutions", "lab", "labs", "laboratories",
    "networks", "software", "security", "capital", "partners", "ventures",
    "bank", "university", "institute", "foundation", "agency", "bureau",
    "industries", "international", "global", "media", "digital", "consulting",
})

# Minimum canonical-key length — drops junk snapshot entries like "$$$" (which
# canonicalise to "") or single stray characters that would over-match.
_MIN_KEY_LEN = 2

_loaded = False
_actors: dict[str, dict[str, Any]] = {}
_malware: dict[str, dict[str, Any]] = {}
_ransomware: dict[str, dict[str, Any]] = {}
_generated_at: Optional[str] = None
_generic_terms: frozenset[str] = frozenset()


def _canonical_key(name: str) -> str:
    """Canonical lookup key — must mirror normalizer canonicalisation for
    THREAT_ACTOR_HANDLE / MALWARE_FAMILY / RANSOMWARE_GROUP so an extracted
    entity's canonical value lines up with a gazetteer entry."""
    if not name:
        return ""
    if name.isascii() and name.isalnum():
        return name.lower()
    v = unicodedata.normalize("NFKD", name)
    v = v.encode("ascii", "ignore").decode("ascii")
    v = v.lower()
    v = re.sub(r"[\s\-_.]", "", v)
    v = re.sub(r"[^\w]", "", v)
    return v


def _keyset(names) -> frozenset[str]:
    out: set[str] = set()
    for n in names or []:
        k = _canonical_key(n)
        if len(k) >= _MIN_KEY_LEN:
            out.add(k)
    return frozenset(out)


def _index_records(records: Any) -> tuple[dict[str, dict[str, Any]], int]:
    """Build an alias-to-record index while accepting the legacy flat format."""
    index: dict[str, dict[str, Any]] = {}
    cluster_count = 0
    for item in records or []:
        if isinstance(item, str):
            record = {"canonical": item, "synonyms": [], "uuid": ""}
        elif isinstance(item, dict):
            canonical = item.get("canonical")
            uuid = item.get("uuid", "")
            synonyms = item.get("synonyms", [])
            if not isinstance(canonical, str) or not canonical.strip():
                continue
            if not isinstance(synonyms, list):
                synonyms = [synonyms] if isinstance(synonyms, str) else []
            record = {
                "canonical": canonical.strip(),
                "synonyms": [s.strip() for s in synonyms if isinstance(s, str) and s.strip()],
                "uuid": uuid.strip() if isinstance(uuid, str) else "",
            }
        else:
            continue

        cluster_count += 1
        for term in (record["canonical"], *record["synonyms"]):
            key = _canonical_key(term)
            if len(key) >= _MIN_KEY_LEN:
                # A first match is deterministic if upstream data contains a
                # colliding alias, and avoids changing existing membership semantics.
                index.setdefault(key, record)
    return index, cluster_count


def _load_generic_terms() -> frozenset[str]:
    """Load generic edge qualifiers used for suffix/prefix retry matching."""
    terms = set(ORG_SUFFIXES)
    try:
        with open(_DOMAIN_STOPWORDS_PATH, encoding="utf-8") as fh:
            terms.update(line.strip().lower() for line in fh if line.strip())
    except FileNotFoundError:
        logger.warning("Domain stopword lexicon not found at %s", _DOMAIN_STOPWORDS_PATH)
    return frozenset(terms)


def _lookup_keys(name: str) -> tuple[str, ...]:
    """Return the original key and edge-stripped retry keys for *name*."""
    original = _canonical_key(name)
    if not name:
        return (original,)
    if name.isascii() and name.isalnum():
        return (original,)

    terms = _generic_terms
    tokens = re.findall(r"[A-Za-z0-9]+", name.lower())
    while tokens and tokens[0] in terms:
        tokens.pop(0)
    while tokens and tokens[-1] in terms:
        tokens.pop()

    stripped = _canonical_key(" ".join(tokens))
    if stripped and stripped != original:
        return (original, stripped)
    return (original,)


def _load() -> None:
    global _loaded, _actors, _malware, _ransomware, _generated_at, _generic_terms
    if _loaded:
        return
    _loaded = True
    try:
        with open(_DATA_PATH, encoding="utf-8") as fh:
            data = json.load(fh)
        _actors, actor_clusters = _index_records(data.get("threat_actors"))
        _malware, malware_clusters = _index_records(data.get("malware"))
        _ransomware, ransomware_clusters = _index_records(data.get("ransomware"))
        _generated_at = data.get("generated_at")
        _generic_terms = _load_generic_terms()
        logger.info(
            "Gazetteer loaded: %d actor names (%d clusters), %d malware names (%d clusters), "
            "%d ransomware names (%d clusters) (generated %s)",
            len(_actors), actor_clusters, len(_malware), malware_clusters,
            len(_ransomware), ransomware_clusters, _generated_at,
        )
    except FileNotFoundError:
        logger.warning(
            "Gazetteer snapshot not found at %s — shape checks will run without "
            "the known-good reference set. Regenerate with "
            "scripts/update_gazetteer.py.",
            _DATA_PATH,
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning("Failed to load gazetteer (non-fatal): %s", exc)


def is_known_actor(name: str) -> bool:
    _load()
    return any(key in _actors for key in _lookup_keys(name))


def is_known_malware(name: str) -> bool:
    _load()
    return any(key in _malware for key in _lookup_keys(name))


def is_known_ransomware(name: str) -> bool:
    _load()
    return any(key in _ransomware for key in _lookup_keys(name))


def is_known(name: str, category: str) -> bool:
    if category in ("threat_actor", "THREAT_ACTOR_HANDLE", "actor"):
        return is_known_actor(name)
    if category in ("malware", "MALWARE_FAMILY"):
        return is_known_malware(name)
    if category in ("ransomware", "RANSOMWARE_GROUP"):
        return is_known_ransomware(name)
    return False


def category_of(name: str) -> Optional[str]:
    """Return the most specific known category for *name*, or None."""
    _load()
    keys = _lookup_keys(name)
    if any(key in _ransomware for key in keys):
        return "ransomware"
    if any(key in _malware for key in keys):
        return "malware"
    if any(key in _actors for key in keys):
        return "threat_actor"
    return None


def lookup(name: str, category: Optional[str] = None) -> Optional[dict[str, Any]]:
    """Return the cluster record for *name*, including its canonical and aliases.

    Alias keys are indexed at load time, so the query-time lookup remains a
    constant-time dictionary operation (apart from the existing edge-stripping
    retries).  A copy is returned so callers cannot mutate the loaded snapshot.
    """
    _load()
    if category in ("threat_actor", "THREAT_ACTOR_HANDLE", "actor"):
        indexes = (_actors,)
    elif category in ("malware", "MALWARE_FAMILY"):
        indexes = (_malware,)
    elif category in ("ransomware", "RANSOMWARE_GROUP"):
        indexes = (_ransomware,)
    elif category is None:
        indexes = (_ransomware, _malware, _actors)
    else:
        return None

    for key in _lookup_keys(name):
        for index in indexes:
            record = index.get(key)
            if record is not None:
                return {**record, "synonyms": list(record["synonyms"])}
    return None


def stats() -> dict:
    _load()
    return {
        "actors": len(_actors),
        "malware": len(_malware),
        "ransomware": len(_ransomware),
        "generated_at": _generated_at,
    }
